# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc881e40a5073145463df7c53953e85c2df583533a55e2e7bfa9c167de039d1b9a3c09dea3b565e4ced45ff5985397d08f9f3cde8acdbac672909dcb47e1ec9b

test:
  secret_key_base: ba616bf73e143536cca037a44daf7cb108826f6da27c9a3e5be380d3bb3affa23697506e1eff66ec8635e28600f67b98d3908cc91ee061719ea3aed908ab98ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
